# Generated by Django 4.1.1 on 2022-11-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('isactive', models.IntegerField()),
                ('creationdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'states',
                'managed': False,
            },
        ),
    ]
